# Generated by Django 3.2.15 on 2025-10-16 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('original_topic', models.TextField(verbose_name='原始主题')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败'), ('paused', '已暂停')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('prompt_template_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='prompts.prompttemplateset', verbose_name='提示词集')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectModelConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('load_balance_strategy', models.CharField(choices=[('round_robin', '轮询'), ('random', '随机'), ('weighted', '权重随机'), ('least_loaded', '最少负载')], default='weighted', max_length=20, verbose_name='负载均衡策略')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('camera_providers', models.ManyToManyField(blank=True, related_name='camera_configs', to='models.ModelProvider', verbose_name='运镜生成模型')),
                ('image_providers', models.ManyToManyField(blank=True, related_name='image_configs', to='models.ModelProvider', verbose_name='文生图模型')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_config', to='projects.project', verbose_name='项目')),
                ('rewrite_providers', models.ManyToManyField(blank=True, related_name='rewrite_configs', to='models.ModelProvider', verbose_name='文案改写模型')),
                ('storyboard_providers', models.ManyToManyField(blank=True, related_name='storyboard_configs', to='models.ModelProvider', verbose_name='分镜生成模型')),
                ('video_providers', models.ManyToManyField(blank=True, related_name='video_configs', to='models.ModelProvider', verbose_name='图生视频模型')),
            ],
            options={
                'verbose_name': '项目模型配置',
                'verbose_name_plural': '项目模型配置',
                'db_table': 'project_model_configs',
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_type', models.CharField(choices=[('rewrite', '文案改写'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频')], max_length=20, verbose_name='阶段类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('input_data', models.JSONField(blank=True, default=dict, verbose_name='输入数据')),
                ('output_data', models.JSONField(blank=True, default=dict, verbose_name='输出数据')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('max_retries', models.IntegerField(default=3, verbose_name='最大重试次数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project', verbose_name='项目')),
            ],
            options={
                'verbose_name': '项目阶段',
                'verbose_name_plural': '项目阶段',
                'db_table': 'project_stages',
                'ordering': ['created_at'],
                'unique_together': {('project', 'stage_type')},
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'status', '-created_at'], name='projects_user_id_5d20b1_idx'),
        ),
    ]
