# Generated by Django 3.2.15 on 2025-11-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprovider',
            name='executor_class',
            field=models.CharField(blank=True, default='', help_text='执行器的完整类路径，如: core.ai_client.openai_client.OpenAIClient', max_length=255, verbose_name='执行器类'),
        ),
        migrations.AlterField(
            model_name='modelprovider',
            name='provider_type',
            field=models.CharField(choices=[('llm', 'LLM模型'), ('text2image', '文生图模型'), ('image2video', '图生视频模型')], max_length=20, verbose_name='模型作用分类'),
        ),
    ]
