# Generated by Django 3.2.15 on 2025-11-04 02:19

from django.db import migrations


def set_default_executors(apps, schema_editor):
    """
    为现有的ModelProvider记录设置默认执行器
    根据provider_type自动分配对应的执行器类路径
    """
    ModelProvider = apps.get_model('models', 'ModelProvider')

    # 定义默认执行器映射
    default_executors = {
        'llm': 'core.ai_client.openai_client.OpenAIClient',
        'text2image': 'core.ai_client.text2image_client.Text2ImageClient',
        'image2video': 'core.ai_client.image2video_client.Image2VideoClient',
    }

    # 更新所有executor_class为空的记录
    for provider in ModelProvider.objects.filter(executor_class=''):
        executor_class = default_executors.get(provider.provider_type)
        if executor_class:
            provider.executor_class = executor_class
            provider.save(update_fields=['executor_class'])
            print(f"已为 '{provider.name}' 设置默认执行器: {executor_class}")


def reverse_set_default_executors(apps, schema_editor):
    """
    回滚操作：清空executor_class字段
    """
    ModelProvider = apps.get_model('models', 'ModelProvider')
    ModelProvider.objects.all().update(executor_class='')


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20251104_1015'),
    ]

    operations = [
        migrations.RunPython(set_default_executors, reverse_set_default_executors),
    ]
