# Generated by Django 3.2.15 on 2026-01-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_create_mock_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelprovider',
            name='api_key',
            field=models.CharField(max_length=2048, verbose_name='API密钥'),
        ),
    ]
