# Generated by Django 3.2.15 on 2025-10-16 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplateSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_sets', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '提示词集',
                'verbose_name_plural': '提示词集',
                'db_table': 'prompt_template_sets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_type', models.CharField(choices=[('rewrite', '文案改写'), ('storyboard', '分镜生成'), ('image_generation', '文生图'), ('camera_movement', '运镜生成'), ('video_generation', '图生视频')], max_length=20, verbose_name='阶段类型')),
                ('template_content', models.TextField(verbose_name='模板内容')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='变量定义')),
                ('version', models.IntegerField(default=1, verbose_name='版本')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('template_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='prompts.prompttemplateset', verbose_name='提示词集')),
            ],
            options={
                'verbose_name': '提示词模板',
                'verbose_name_plural': '提示词模板',
                'db_table': 'prompt_templates',
            },
        ),
        migrations.AddIndex(
            model_name='prompttemplateset',
            index=models.Index(fields=['is_active', 'is_default'], name='prompt_temp_is_acti_d5ab82_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['template_set', 'stage_type', 'is_active'], name='prompt_temp_templat_a85d4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prompttemplate',
            unique_together={('template_set', 'stage_type')},
        ),
    ]
