# Generated by Django 3.2.15 on 2025-10-16 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
        ('prompts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='model_provider',
            field=models.ForeignKey(blank=True, help_text='该提示词模板默认使用的AI模型', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_templates', to='models.modelprovider', verbose_name='模型提供商'),
        ),
    ]
