# Generated by Django 3.2.15

from django.db import migrations
import uuid


def create_mock_prompt_template_set(apps, schema_editor):
    """
    创建 Mock API 的提示词模板集
    包含所有阶段的简化提示词模板
    """
    PromptTemplateSet = apps.get_model('prompts', 'PromptTemplateSet')
    PromptTemplate = apps.get_model('prompts', 'PromptTemplate')
    ModelProvider = apps.get_model('models', 'ModelProvider')
    User = apps.get_model('auth', 'User')

    # 获取或创建系统用户
    system_user, _ = User.objects.get_or_create(
        username='system',
        defaults={
            'email': 'system@example.com',
            'is_staff': True,
            'is_superuser': False
        }
    )

    # 获取 Mock 模型提供商
    try:
        mock_llm = ModelProvider.objects.get(name='Mock LLM API')
        mock_text2image = ModelProvider.objects.get(name='Mock Text2Image API')
        mock_image2video = ModelProvider.objects.get(name='Mock Image2Video API')
    except ModelProvider.DoesNotExist:
        print("⚠ 警告: Mock API 提供商不存在，请先运行 models app 的迁移")
        return

    # 创建提示词集
    template_set, created = PromptTemplateSet.objects.get_or_create(
        name='Mock API 测试模板集',
        defaults={
            'id': uuid.uuid4(),
            'description': 'Mock API 专用的简化提示词模板，用于快速测试工作流',
            'is_active': True,
            'is_default': False,
            'created_by': system_user
        }
    )

    if not created:
        print(f"✓ 提示词集已存在: {template_set.name}")
        return

    print(f"✓ 已创建提示词集: {template_set.name}")

    # 创建各阶段的提示词模板
    templates = [
        {
            'stage_type': 'rewrite',
            'model_provider': mock_llm,
            'template_content': '''
# 角色
你是一位经验丰富的短剧剧本创作大师，擅长在有限的时间内（例如30秒）构建紧凑且富有张力的故事线。你的剧本内容完整且节奏快速，特别擅长创作动漫风格的短剧，尤其是只有一个角色的剧本。
请对以下内容进行改写和优化：

原始内容：
{{ original_content }}

要求：
1. 编写紧凑故事脚本 - 在30秒内构建完整且吸引人的故事弧线，包括开头、发展、冲突与高潮以及结尾。
2. 设计角色性格鲜明，对话生动有力，有效推动剧情进展。
3. 确保剧本在有限时间内传达清晰的故事主线和情感表达。
4. 采用宫崎骏风格的叙事手法，注重细腻的情感描绘和独特的视觉效果。
5. 创造充满幻想和想象力的场景，如自然景观、神秘生物等。
6. 通过角色的内心独白或动作表现，传达深刻的主题和情感。
7. 专注于一个角色的内心世界和情感变化，通过该角色的行为和环境互动展现故事。
8. 利用旁白、内心独白或肢体语言来丰富角色的表现力。
9. 确保单角色剧本依然具有足够的戏剧张力和吸引力。
10. 剧本应保持动漫风格的特点，如细腻的情感描绘、幻想元素和独特的视觉效果。
11. 剧本时长严格控制在30秒以内。
12. 适合用于视频脚本
13. 字数控制在 {{ max_length|default(500) }} 字以内

请直接输出改写后的内容。''',
            'variables': {
                'original_content': {'type': 'string', 'required': True, 'description': '原始内容'},
                'max_length': {'type': 'int', 'required': False, 'default': 500, 'description': '最大字数'}
            }
        },
        {
            'stage_type': 'storyboard',
            'model_provider': mock_llm,
            'template_content': '''
# 角色\n你是一位经验丰富的分镜剧本创作专家，擅长将剧本转化为详细的分镜描述，并以JSON格式输出
请根据以下内容生成分镜脚本：

内容：
{{ rewritten_content }}

要求：
1. 根据提供的剧本内容，生成 {{ scene_count|default(3) }} 个场景
2. 每个场景包含：场景描述、旁白文字、图片提示词、时长、运镜方式
3. 分镜应包括场景描述、角色动作、对话和必要的视觉效果，确保每个分镜都清晰、具体且具有可拍摄性
4. 以 JSON 数组格式输出

输出格式示例：
{
  "scenes": [
    {
      "scene_number": 1,
      "narration": "旁白文本",
      "visual_prompt": "视觉提示词",
      "shot_type": "镜头类型"
    }
  ]
}

请直接输出 JSON 数组。''',
            'variables': {
                'rewritten_content': {'type': 'string', 'required': True, 'description': '改写后的内容'},
                'scene_count': {'type': 'int', 'required': False, 'default': 3, 'description': '场景数量'}
            }
        },
        {
            'stage_type': 'image_generation',
            'model_provider': mock_text2image,
            'template_content': '''
# 角色\n你是一位创意十足的视觉艺术家，擅长根据剧本内容生成人物形象的文字描述，以便生成高质量的动漫风格角色图片。\n\n## 技能\n### 技能1: 生成角色形象描述\n- 根据剧本中的角色描述和情节背景，生成详细且生动的宫崎骏风格角色形象文字描述。\n- 描述应包括角色的外貌特征、服装风格、表情、姿态等，确保能够准确传达角色的性格和情感。\n### 技能2: 角色画风限制\n- 宫崎骏风格\n圆润柔和的线条，大眼睛与富有表现力的面部，自然主义的身体比例，细腻的表情与微动作，服装与环境的高度融合，强调个性而非刻板印象，手绘质感与动态生命力\n### 技能3: 优化提示词\n- 确保生成的提示词简洁明了，不超过300字。\n- 使用具有表现力的语言，使提示词能够激发图像生成工具的创造力。\n- 考虑到不同图像生成工具的特点，提供适合多种工具使用的提示词。\n\n## 限制\n- 输出的提示词必须在300字以内。\n- 提示词应基于剧本内容，不得偏离角色设定。\n- 不得包含任何不适当或敏感的内容。
{{ visual_prompt }}''',
            'variables': {
                'visual_prompt': {'type': 'string', 'required': False, 'description': '视觉提示词（优先使用）'},
                'image_prompt': {'type': 'string', 'required': False, 'description': '图片生成提示词（备用）'}
            }
        },
        {
            'stage_type': 'camera_movement',
            'model_provider': mock_llm,
            'template_content': '''# 角色\n你是一位专业的视频提示词生成专家，擅长根据分镜内容和图片信息生成简洁而准确的分镜视频运镜和动作提示词。你的目标是让静态图片在保持原图内容的基础上动起来，而不添加多余的内容。你参考动漫的设计风格，注重自然流畅的角色动作、真实感与生命力，并遵循物理逻辑和情绪驱动的动作设计。

请为以下场景生成运镜参数：

场景描述：
{{ human_text }}

可用运镜类型：
- 左右移: [左移], [右移]
- 左右摇: [左摇], [右摇]
- 推拉: [推进], [拉远]
- 升降: [上升], [下降]
- 上下摇: [上摇], [下摇]
- 变焦: [变焦推近], [变焦拉远]
- 其他: [晃动], [跟随], [固定]

要求：
- 生成分镜视频提示词，根据提供的分镜内容和图片信息，生成不超过300字的视频提示词。确保提示词简洁明了，只描述如何让图片动起来，不添加额外的创意或内容
- 使用专业术语和清晰的语言，确保动画师能够准确理解并执行
- 分镜设计参考宫崎骏的设计风格：自然流畅的角色动作，真实感与生命力，遵循物理逻辑
- 情绪驱动的动作设计，如千寻初入神隐世界时的迟疑步伐、奔跑时的慌乱，都精准传递其心理状态
- 动作节奏随剧情起伏变化：紧张时快速急促，平静时缓慢平稳。
- 光影与色彩配合运镜：空镜头与引导线构图：善用空镜头（风车、野花、溪流）作为情绪留白，赋予画面“无声的旁白”。利用道路、围栏、河流等自然线条引导观众视线，构建视觉动线，常见于开场与结尾。
- “动中有静，静中有动”：即使在激烈动作中，也保留细腻停顿；在静态画面中，通过光影、微风、水流制造内在动感。
- 以人为本的镜头逻辑：镜头始终围绕角色情感与成长展开，技术服务于叙事，而非炫技。
- 手绘质感 + 电影级调度：虽为动画，但运镜思维完全电影化，媲美真人电影的镜头调度
- 以 JSON 格式输出运镜参数

输出格式示例：
{
  "movement_type": "slow_zoom_in",
  "movement_params": {
    "start_scale": 1.0,
    "end_scale": 1.2,
    "duration": 3.0,
    "easing": "ease_in_out"
  },
  "description": "视频描述"
}

请直接输出 JSON 对象。''',
            'variables': {
                'scene_description': {'type': 'string', 'required': True, 'description': '场景描述'}
            }
        },
        {
            'stage_type': 'video_generation',
            'model_provider': mock_image2video,
            'template_content': '''根据图片和运镜参数生成视频

图片URL: {{ image_url }}
运镜参数: {{ camera_movement }}
时长: {{ duration|default(3.0) }} 秒
帧率: {{ fps|default(24) }} fps''',
            'variables': {
                'image_url': {'type': 'string', 'required': True, 'description': '源图片URL'},
                'camera_movement': {'type': 'json', 'required': True, 'description': '运镜参数'},
                'duration': {'type': 'float', 'required': False, 'default': 3.0, 'description': '视频时长'},
                'fps': {'type': 'int', 'required': False, 'default': 24, 'description': '帧率'}
            }
        }
    ]

    # 创建模板
    stage_names = {
        'rewrite': '文案改写',
        'storyboard': '分镜生成',
        'image_generation': '文生图',
        'camera_movement': '运镜生成',
        'video_generation': '图生视频'
    }

    for template_data in templates:
        template, created = PromptTemplate.objects.get_or_create(
            template_set=template_set,
            stage_type=template_data['stage_type'],
            defaults={
                'id': uuid.uuid4(),
                'model_provider': template_data['model_provider'],
                'template_content': template_data['template_content'],
                'variables': template_data['variables'],
                'version': 1,
                'is_active': True
            }
        )
        if created:
            stage_name = stage_names.get(template_data['stage_type'])
            print(f"  ✓ 已创建模板: {stage_name}")

    print("\n✓ Mock API 提示词模板集创建完成！")
    print("  包含 5 个阶段的模板：")
    print("  - 文案改写 (rewrite)")
    print("  - 分镜生成 (storyboard)")
    print("  - 文生图 (image_generation)")
    print("  - 运镜生成 (camera_movement)")
    print("  - 图生视频 (video_generation)")


def remove_mock_prompt_template_set(apps, schema_editor):
    """
    回滚操作：删除 Mock API 提示词模板集
    """
    PromptTemplateSet = apps.get_model('prompts', 'PromptTemplateSet')

    deleted_count = PromptTemplateSet.objects.filter(
        name='Mock API 测试模板集'
    ).delete()[0]

    print(f"✓ 已删除 Mock API 提示词模板集（共 {deleted_count} 条记录）")


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0004_auto_20251215_1049'),
        ('models', '0004_create_mock_providers'),  # 依赖 Mock 提供商
    ]

    operations = [
        migrations.RunPython(
            create_mock_prompt_template_set,
            remove_mock_prompt_template_set
        ),
    ]
